### ISSUE TITLE
The URL was blocked by a content blocker (WebKitErrorDomain:104)

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardBrowserExtension#466]
STR:
1. go to 11street.my
2. try to search anything

AR: Error appear: The URL was blocked by a content blocker (WebKitErrorDomain:104)
Reloading the page makes it load properly.

Reported by user **1456836**, also a relevant thread here:
https://discussions.apple.com/thread/7710782

Reproduced with Safari 10 on macOS Sierra with Adguard 2.5.3

**Comment by ameshkov** [comment]
@Bohdan-SUP cannot reproduce it in Safari version 10.0.2 (12602.3.10).

Which filters should I enable?

**Comment by Bohdan-SUP** [comment]
Checked with Safari 10.0.1 (12602.2.14.0.7) and Adguard 2.5.3 extension.
English filter is breaking it on my side.

**Comment by ameshkov** [comment]
I suppose the issue is fixed in the newer Safari version.

@Bohdan-SUP try Safari Technology preview, is it good?

**Comment by Bohdan-SUP** [comment]
Still a no go - the same webkit error in Safari Technology Preview Release 18 (Safari 10.1, WebKit 12603.1.12) :(

**Comment by ameshkov** [comment]
Updated Safari filter, should be ok now:
https://github.com/AdguardTeam/AdguardFilters/commit/c73ea69467dd46c6022df909e200fcd718a34a6b

**Comment by jwchong** [comment]
Tried in iOS Safari with Safari filter updated to 1.0.1.81, issue still there.

**Comment by ameshkov** [comment]
@jwchong it will be ok in the next iOS version (once we update converter version).

**Comment by ameshkov** [comment]
@jwchong hm, i may be wrong though, let's double-check.

@vozersky could you please assist me on this?

**Comment by quicksite** [comment]
Interestingly enough, a year later, and I've been getting this error recently:

Safari can’t open the page
The error is: “The URL was blocked by a content blocker” (WebKitErrorDomain:104)

![by default 2017-12-13 at 4 29 12 pm](https://user-images.githubusercontent.com/128756/33969596-03357c54-e023-11e7-9802-4ed441aa1512.png)

**Here's the URL i was trying to open:**
https://www.theatlantic.com/technology/archive/2014/08/advertising-is-the-internets-original-sin/376041/

I'm not sophisticated enough a user to know what I need to do

**Comment by quicksite** [comment]
Searching "The error is: “The URL was blocked by a content blocker” (WebKitErrorDomain:104)", two hits:

(1) Reddit:  10/2017
https://www.reddit.com/r/Adguard/comments/71ljtr/macos_safari_11_content_blocking_vs_adguard/
![by default 2017-12-13 at 4 44 49 pm](https://user-images.githubusercontent.com/128756/33969942-46296d16-e025-11e7-86d4-2b81fdee8fff.png)

(2) Apple Community forum: 10/16/16
https://discussions.apple.com/thread/7710782
![by default 2017-12-13 at 4 37 59 pm](https://user-images.githubusercontent.com/128756/33969857-ce7927ca-e024-11e7-83b6-da2dabe21a99.png)

**Comment by quicksite** [comment]
Solution for me:  
Turns out I didn't even have AdGuard installed on Safari. But I did have uBlock Origin 1.11.3.1 and Adblock Plus 1.12.4 installed. I had to whitelist the offending site ( theatlantic.com ) in both blockers. Now the page displays correctly.

**Comment by ericdgit** [comment]
The problem (not showing the Atlantic article) seems to correlate with the url having the word "advertising" in it.. I had the same problem on a website I am developing. For me it looks like a bug in AdBlock.
